name: Lint Terraform module

on:
  workflow_call:
    inputs:
      terraform-version:
        description: The version of Terraform to set up.
        default: latest
        required: false
        type: string
      tflint-version:
        description: The version of TFLint to set up.
        default: latest
        required: false
        type: string
    secrets:
      access-token:
        description: A personal access token to use for GitHub authentication.
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      access_token: ${{ secrets.access-token }}
    steps:
      - name: Clone the source code
        uses: actions/checkout@v5.0.0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v6.1.0
        with:
          tflint_version: ${{ inputs.tflint-version }}

      - name: Set up GitHub authentication
        if: ${{ env.access_token != '' }}
        run: |
          echo "${access_token}" | gh auth login --with-token
          gh auth setup-git
          gh auth status

      - name: Initialize Terraform
        run: terraform init

      - name: Check formatting
        run: terraform fmt -check -diff

      - name: Validate Terraform
        run: terraform validate

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
